# RRA Module - Blockchain Licensing Configuration
# This file defines how this repository is monetized on-chain via automated agent negotiation

# Base License Information
license_identifier: "FSL-1.1-ALv2"
copyright_holder: "Kase Branham"
copyright_year: 2025

# Pricing Configuration
license_model: "perpetual"  # Options: per-seat, subscription, one-time, perpetual, custom
target_price: "0.005 ETH"   # One-time payment for perpetual license (test price)
floor_price: "0.002 ETH"   # Minimum acceptable price (agents won't go below this)
ceiling_price: "0.15 ETH"  # Maximum price for premium features

# Negotiation Agent Configuration
negotiation_style: "persuasive"  # Options: concise, persuasive, strict, adaptive
agent_personality: "Professional" # How the agent presents the repository
negotiation_rounds_max: 5         # Maximum back-and-forth negotiations

# Licensing Terms Available On-Chain
license_terms:
  # What buyers get with standard license
  standard:
    features:
      - "Full source code access"
      - "Production deployment rights"
      - "Updates for 12 months"
      - "Community support via GitHub Issues"
      - "Commercial use (non-competing)"
    price_multiplier: 1.0

  # Premium tier options
  premium:
    features:
      - "Priority support (48hr response)"
      - "Custom feature requests"
      - "Fork rights for internal modifications"
      - "Unlimited production deployments"
      - "License transfers allowed"
    price_multiplier: 2.5  # 2.5x standard price

  # Enterprise tier
  enterprise:
    features:
      - "Dedicated support channel"
      - "Custom integrations assistance"
      - "White-label permissions"
      - "Competing use allowance (limited)"
      - "Perpetual license with unlimited seats"
    price_multiplier: 5.0

# Smart Contract Configuration
blockchain:
  network: "ethereum"  # Options: ethereum, polygon, arbitrum, base
  contract_version: "1.0"

  # Revenue distribution (on-chain splits)
  revenue_split:
    developer: 91  # Percentage to original developer
    platform: 8    # Percentage to NatLangChain platform
    community: 1   # Percentage to community treasury

  # Wallet addresses for revenue distribution
  wallets:
    developer: "0x28AF4381Fe546CAe46f2B390360FF9D4F8B1C418"  # Developer wallet - receives 91%
    platform: "0x28AF4381Fe546CAe46f2B390360FF9D4F8B1C418"   # Platform fee wallet - receives 8%
    community: "0x28AF4381Fe546CAe46f2B390360FF9D4F8B1C418"  # Community treasury - receives 1%

  # NFT License Token Configuration
  nft_config:
    token_standard: "ERC-721"  # Each license is unique NFT
    transferable: true          # Licenses can be resold
    revocable: false           # Cannot be revoked after sale
    expiry_enabled: false      # Perpetual license - never expires

# Repository Features (for agent marketing)
features:
  - "AI-Driven Negotiation Agents"
  - "Blockchain License Management"
  - "GitHub Integration"
  - "Automated Revenue Distribution"
  - "Knowledge Base Generation"

# Technical Specifications (for verification)
repository:
  languages: ["Python"]
  total_files: 31
  test_coverage: "85%"
  documentation: "Comprehensive"
  examples: "Included"

# Verification & Quality Gates
verification:
  # Test suite that buyers can run to verify functionality
  sandbox_tests: "tests/"

  # Automated quality checks
  quality_gates:
    - "All tests passing"
    - "License compliance verified"
    - "Documentation complete"
    - "Security audit passed"

  # On-chain attestations
  attestations:
    code_quality: true      # Verified via CI/CD
    license_compliance: true # Verified via license-verification.yml
    security_scan: true     # Verified via security tools

# Update & Maintenance
updates:
  frequency: "weekly"       # How often repo is re-ingested
  notification: "on-chain"  # Notify license holders of updates
  breaking_changes: "notify-with-upgrade-option"

# Buyer Requirements
buyer_requirements:
  # Minimum requirements to purchase license
  min_reputation: 0        # No minimum (open marketplace)
  kyc_required: false      # No KYC for decentralized sales
  payment_methods:
    - "ETH"
    - "USDC"
    - "DAI"

# DeFi Protocol Integration Settings
defi_integrations:
  # Story Protocol - Programmable IP Licensing (Phase 3)
  story_protocol:
    enabled: true  # Story Protocol integration is now active
    ip_asset_id: "0xf08574c30337dde7C38869b8d399BA07ab23a07F"  # Mainnet IP Asset ID (registered 2025-01)
    network: "mainnet"  # Options: mainnet, testnet

    # License Terms Configuration (for purchases)
    license_terms_id: 28437  # Custom terms with 0.005 ETH minting fee and LAP royalty policy

    # Programmable IP License (PIL) Terms
    pil_terms:
      commercial_use: true              # Allow commercial use of licensed code
      derivatives_allowed: true         # Allow forks and derivative works
      derivatives_attribution: true     # Require attribution in derivatives
      derivatives_reciprocal: false     # Copyleft requirement (false = permissive)

    # Derivative Royalty Configuration
    derivative_royalty_percentage: 0.09  # 9% royalty on derivative revenues (matches 8% platform + 1% community)
    payment_token: "ETH"  # Options: ETH, USDC, DAI

    # Automatic Derivative Tracking
    auto_track_forks: true  # Automatically detect and register GitHub forks
    require_fork_registration: false  # Require forks to register as derivatives

    # Purchase Configuration
    purchase_enabled: true  # Enable direct license purchases
    explorer_url: "https://explorer.story.foundation/ipa/0xf08574c30337dde7C38869b8d399BA07ab23a07F"

# Custom Clauses (Blockchain-Enforced)
custom_clauses:
  - id: "non-competing-use"
    description: "Cannot use to build competing RRA systems"
    enforced_by: "license-terms"

  - id: "attribution-required"
    description: "Must maintain copyright notices and SPDX headers"
    enforced_by: "smart-contract"

  - id: "future-license-grant"
    description: "Automatically becomes Apache 2.0 after 2 years"
    enforced_by: "time-lock-contract"
    effective_date: "2027-12-19"

# Agent Behavior Modifiers
agent_behavior:
  # How aggressive is pricing?
  pricing_flexibility: 0.6  # 0.0 = rigid, 1.0 = very flexible

  # Respond to these buyer signals
  respond_to_volume_discount: true  # Offer discounts for bulk purchases
  respond_to_reputation: true        # Better terms for high-rep buyers
  respond_to_open_source_use: true  # Special pricing for OSS projects

  # Marketing approach
  highlight_features: true   # Proactively mention key features
  offer_demos: true         # Offer sandbox/demo access
  provide_metrics: true     # Share repo statistics and quality metrics

# Marketplace Settings
marketplace:
  visibility: "public"      # Publicly listed in NatLangChain marketplace
  categories:
    - "AI/ML"
    - "Blockchain"
    - "Developer Tools"
    - "Automation"

  tags:
    - "ai-agents"
    - "blockchain-licensing"
    - "github-integration"
    - "automated-monetization"
    - "smart-contracts"

# Analytics & Reporting
analytics:
  track_negotiations: true   # Log all negotiation sessions (privacy-preserving)
  track_conversions: true    # Monitor negotiation → sale conversion rate
  track_revenue: true        # On-chain revenue tracking
  publish_stats: "aggregated" # Share anonymized statistics

# Emergency Controls
emergency:
  pause_sales: false         # Can pause new sales if issues found
  revoke_existing: false     # Cannot revoke existing licenses
  update_terms: "new-sales-only"  # Term updates only affect new sales

# Contact & Support
support:
  method: "github-issues"
  response_time: "48-72 hours"
  emergency_contact: "github.com/kase1111-hash/RRA-Module/issues"

# Metadata
metadata:
  version: "1.0.0"
  last_updated: "2025-12-19"
  ingested: false  # Set to true after first ingestion
  agent_id: null   # Populated when agent is spawned
  contract_address: null  # Populated when deployed to blockchain
