name: Feature Request
description: Suggest a new feature or enhancement for RRA Module
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea clearly so we can evaluate it.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is there a frustration or limitation you're experiencing?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Which part of RRA Module does this relate to?
      options:
        - CLI (Command Line Interface)
        - API Server
        - Negotiation Agents
        - Smart Contracts
        - Ingestion/Parsing
        - Blockchain Integration (new chain support, etc.)
        - Authentication
        - Cryptographic Operations
        - DeFi Features
        - Governance/DAO
        - Reputation System
        - Configuration
        - Documentation
        - NatLangChain Integration
        - Story Protocol Integration
        - Mobile SDK
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would improve my workflow
        - Important for my use case
        - Critical blocker
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case. How would you use this feature?
      placeholder: |
        As a [type of user], I want to [do something] so that [benefit].

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas (Optional)
      description: If you have technical ideas on how this could be implemented, share them here.

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to help implement this feature
          required: false
        - label: I would be willing to help test this feature
          required: false
        - label: I would be willing to help document this feature
          required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this hasn't been requested
          required: true
        - label: I have checked the [roadmap](https://github.com/kase1111-hash/RRA-Module/blob/main/ROADMAP.md) for planned features
          required: false
