// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Script, console} from "forge-std/Script.sol";
import {ILRM} from "../src/ILRM.sol";
import {ComplianceEscrow} from "../src/ComplianceEscrow.sol";
import {BatchQueue} from "../src/BatchQueue.sol";

/**
 * @title DeployZKInfrastructure
 * @notice Deployment script for Phase 5 ZK privacy infrastructure
 *
 * Deployment Order:
 * 1. Deploy mock Groth16Verifier (or use real one from Circom)
 * 2. Deploy ILRM with verifier address
 * 3. Deploy ComplianceEscrow
 * 4. Deploy BatchQueue with ILRM address
 *
 * Usage:
 *   # Local (anvil)
 *   forge script script/DeployZKInfrastructure.s.sol --rpc-url localhost --broadcast
 *
 *   # Sepolia testnet
 *   forge script script/DeployZKInfrastructure.s.sol --rpc-url sepolia --broadcast --verify
 */
contract DeployZKInfrastructure is Script {
    function setUp() public {}

    function run() public {
        uint256 deployerPrivateKey = vm.envUint("PRIVATE_KEY");
        address deployer = vm.addr(deployerPrivateKey);

        console.log("=== Phase 5: ZK Infrastructure Deployment ===");
        console.log("Deployer:", deployer);
        console.log("Chain ID:", block.chainid);
        console.log("");

        vm.startBroadcast(deployerPrivateKey);

        // 1. Deploy Mock Verifier (replace with real Circom-generated verifier in production)
        MockGroth16Verifier verifier = new MockGroth16Verifier();
        console.log("1. MockGroth16Verifier deployed:", address(verifier));

        // 2. Deploy ILRM
        ILRM ilrm = new ILRM(address(verifier));
        console.log("2. ILRM deployed:", address(ilrm));

        // 3. Deploy ComplianceEscrow
        ComplianceEscrow escrow = new ComplianceEscrow();
        console.log("3. ComplianceEscrow deployed:", address(escrow));

        // 4. Deploy BatchQueue
        BatchQueue batchQueue = new BatchQueue(address(ilrm), deployer);
        console.log("4. BatchQueue deployed:", address(batchQueue));

        vm.stopBroadcast();

        // Output summary
        console.log("");
        console.log("=== Deployment Summary ===");
        console.log("Network:", _getNetworkName());
        console.log("");
        console.log("Contracts:");
        console.log("  Groth16Verifier:", address(verifier));
        console.log("  ILRM:           ", address(ilrm));
        console.log("  ComplianceEscrow:", address(escrow));
        console.log("  BatchQueue:     ", address(batchQueue));
        console.log("");
        console.log("Next Steps:");
        console.log("1. Generate real Groth16Verifier from Circom circuits");
        console.log("2. Update ILRM.updateVerifier() with real verifier");
        console.log("3. Configure ComplianceEscrow roles");
        console.log("4. Fund BatchQueue treasury for dummy transactions");
    }

    function _getNetworkName() internal view returns (string memory) {
        if (block.chainid == 1) return "Ethereum Mainnet";
        if (block.chainid == 11155111) return "Sepolia";
        if (block.chainid == 421614) return "Arbitrum Sepolia";
        if (block.chainid == 11155420) return "Optimism Sepolia";
        if (block.chainid == 84532) return "Base Sepolia";
        if (block.chainid == 31337) return "Localhost (Anvil)";
        return "Unknown";
    }
}

/**
 * @title MockGroth16Verifier
 * @notice Mock verifier for testing (always returns true)
 * @dev Replace with real Circom-generated verifier for production
 */
contract MockGroth16Verifier {
    function verifyProof(
        uint[2] calldata,
        uint[2][2] calldata,
        uint[2] calldata,
        uint[1] calldata
    ) external pure returns (bool) {
        // MOCK: Always returns true
        // In production, use the verifier generated by:
        // snarkjs zkey export solidityverifier build/prove_identity.zkey Groth16Verifier.sol
        return true;
    }
}
